/**
 * backfillCanon.ts — Phase 2.2 Canon Backfill Function
 *
 * Purpose: Extract canon data from existing project (memory + architecture + text)
 *
 * Usage (from UI or script):
 *   import { backfillProjectCanon } from './canon/backfillCanon';
 *   await backfillProjectCanon(project, firestoreUpdateFn);
 *
 * Process:
 *   1. Call AIEngine with EXTRACT_CANON mode
 *   2. Post-process with asInferredCanon() (stamps origin as inferred+confirmed:false)
 *   3. Return inferred canon for Firestore update
 *
 * Idempotency:
 *   - Stable IDs generated by AI (reuse same id for recurring entities)
 *   - Dedupe by name (case-insensitive)
 *   - Safe to re-run (returns fresh extraction)
 *
 * Guards (Phase 2):
 *   - Everything extracted is inferred (confirmed:false)
 *   - No auto-confirm logic
 *   - memory remains source of truth (canon not used in generation yet)
 */

import { NarrativeMode, NarrativeAspect, type Project } from '../types';
import { generateNarrativeContent } from '../services/AIEngine';
import { asInferredCanon, type ProjectCanon } from './index';

export interface BackfillResult {
  success: boolean;
  canon?: any;
  error?: string;
  stats: {
    characters: number;
    locations: number;
    events: number;
    factions: number;
    artifacts: number;
    worldRules: number;
  };
}

/**
 * Backfills a project with Canon data extracted from memory + architecture + text
 *
 * @param project - The project to backfill
 * @returns BackfillResult with extracted canon data
 */
export async function backfillProjectCanon(project: Project): Promise<BackfillResult> {
  console.log(`[Backfill] Starting canon extraction for project: ${project.id}`);

  try {
    // Step 1: Run EXTRACT_CANON mode via AIEngine
    console.log(`[Backfill] Calling AIEngine with EXTRACT_CANON mode...`);

    const result = await generateNarrativeContent({
      text: project.text || '',
      mode: NarrativeMode.EXTRACT_CANON,
      aspect: NarrativeAspect.PLOT_STRUCTURE, // Not used in EXTRACT_CANON but required by type
      memory: project.memory || { characters: [], locations: [], timeline: [], worldRules: [], plotEvents: [] },
      activeProject: project,
      activeScene: null,
    });

    if (!result?.data) {
      throw new Error('AI returned empty result');
    }

    console.log(`[Backfill] AI extraction complete, raw keys:`, Object.keys(result.data));

    // Step 2: Post-process with asInferredCanon (stamps origin as inferred)
    console.log(`[Backfill] Stamping entities as inferred (confirmed:false)...`);
    const inferredCanon = asInferredCanon(result.data);

    const stats = {
      characters: inferredCanon.characters?.length || 0,
      locations: inferredCanon.locations?.length || 0,
      events: inferredCanon.events?.length || 0,
      factions: inferredCanon.factions?.length || 0,
      artifacts: inferredCanon.artifacts?.length || 0,
      worldRules: inferredCanon.world?.rules?.length || 0,
    };

    console.log(`[Backfill] Extraction stats:`, stats);
    console.log(`[Backfill] ✅ Backfill complete - ready to write to Firestore`);

    return {
      success: true,
      canon: inferredCanon,
      stats,
    };

  } catch (error: any) {
    console.error(`[Backfill] ❌ Error during extraction:`, error.message);
    return {
      success: false,
      error: error.message,
      stats: {
        characters: 0,
        locations: 0,
        events: 0,
        factions: 0,
        artifacts: 0,
        worldRules: 0,
      },
    };
  }
}

/**
 * Validates that extracted canon is well-formed
 */
export function validateCanon(canon: any): { valid: boolean; errors: string[] } {
  const errors: string[] = [];

  if (!canon) {
    errors.push('Canon is null or undefined');
    return { valid: false, errors };
  }

  // Check required arrays exist
  const requiredArrays = ['characters', 'locations', 'events', 'factions', 'artifacts'];
  for (const key of requiredArrays) {
    if (!Array.isArray(canon[key])) {
      errors.push(`Missing or invalid array: ${key}`);
    }
  }

  // Check all entities have required fields
  const checkEntity = (entity: any, index: number, type: string) => {
    if (!entity.id) errors.push(`${type}[${index}]: missing id`);
    if (!entity.name) errors.push(`${type}[${index}]: missing name`);
    if (!entity.origin) errors.push(`${type}[${index}]: missing origin`);
    if (entity.origin && entity.origin.source !== 'inferred') {
      errors.push(`${type}[${index}]: origin.source must be 'inferred', got '${entity.origin.source}'`);
    }
    if (entity.origin && entity.origin.confirmed !== false) {
      errors.push(`${type}[${index}]: origin.confirmed must be false, got '${entity.origin.confirmed}'`);
    }
  };

  canon.characters?.forEach((c: any, i: number) => checkEntity(c, i, 'character'));
  canon.locations?.forEach((l: any, i: number) => checkEntity(l, i, 'location'));
  canon.events?.forEach((e: any, i: number) => checkEntity(e, i, 'event'));

  return { valid: errors.length === 0, errors };
}
